<center style="font-size: 26px"> <b>Проверка уровня знаний Python</b></center>

### Проверка построена следующим образом:

- К каждому блоку приложены практические задания по теме блока
- К каждому практическому заданию приложен либо рабочий файл, либо дано вводное условие
- Для успешного прохождения проверки требуется правильно ответить на 10/15 вопросов
- Корректным ответом на вопрос считается любой работоспособный код, позволяющий достичь корректного результата (и использующий проверяемый синтаксис, если это указано в условии задания)

<center style="background-color: #23B04A; color: white; font-size: 16px"><b>NumPy</b></center>

`Numpy` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.

### Технический код:
Данная часть нужна исключительно для корректной работы данной тетради. Исполните блок (Shift + Enter), не вдаваясь в суть написанного.

In [1]:
# обеспечиваем совместимость с Python 2 и 3
from __future__ import (absolute_import, division, print_function, unicode_literals)

# отключаем предупреждения дистрибутива Anaconda
import warnings
warnings.simplefilter('ignore')

### Практические задания:

In [2]:
# Импортируем библиотеки NumPy и Pandas
import numpy as np
import pandas as pd

#### 1. Создание массивов
Создайте и перемножьте одномерный и двумерный массивы при помощи библиотеки NumPy

In [4]:
first_dim = 10 # Количество элементов в итоговом массиве 
second_dim = 5 # Количество элементов в изначальном массиве
# In: twodim_arr.shape 
# Out: (first_dim_, second_dim)
twodim_arr = np.random.sample((first_dim, second_dim)) 
onedim_arr = np.random.sample(second_dim) 
result = np.dot(twodim_arr, onedim_arr)
result

array([1.47122802, 1.36267933, 1.35280075, 1.38747178, 1.29590897,
       1.22825565, 1.14951033, 1.72325746, 1.40380956, 1.3174231 ])

#### 2. Методы создания массивов
Создайте один и тот же массив 3-мя разными способами при помощи библиотеки NumPy

In [7]:
print(np.arange(1, 4))
print(np.array([1, 2, 3])) # Из list
print(np.fromiter(iter([1, 2, 3]), dtype = int)) # Из итерируемого типа

[1 2 3]
[1 2 3]
[1 2 3]


#### 3. Индексирование массивов

Напишите код, производящий указанные в комментариях операции с массивами

In [8]:
a = np.diag(np.arange(3))  # Выделите значение = 1
a[1,1] 
# Или
a[a == 1] # Будет выбран массив элементов со значением 1 (In: a[a == 1] | Out: [1])

b = np.random.rand(5, 5)  # Выделите первую строку
b[0]

c = np.arange(10) # Присвойте значение = 25 элементам массива с 3 по 6 включительно
c[2:6] = 25 # В случае индексации элементов массива с 1

#### 4. Индексирование масками

Выберите из предоставленного массива значения, делящиеся на 3 без остатка, и присвойте им значение = 10  

In [9]:
np.random.seed(3)
a = np.random.random_integers(0, 20, 15)

print(a)
a[a % 3 == 0] = 10

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]


#### 5. Меры центральной тенденции и меры вариации

Напишите код, находящий указанные в комментариях значения

In [11]:
a = np.linspace(0, 20, 5)  # Найти среднее арифметическое массива
print(np.mean(a))

b = np.linspace(0, 30, 10)  # Найти медианное значение массива
print(np.median(b))

c = np.linspace(0, 10, 10)  # Найти кумулятивную сумму элементов массива
print(np.cumsum(c))

10.0
15.0
[ 0.          1.11111111  3.33333333  6.66666667 11.11111111 16.66666667
 23.33333333 31.11111111 40.         50.        ]


<center style="background-color: #23B04A; color: white; font-size: 16px"><b>Pandas</b></center>

`Pandas` - это библиотека Python, предоставляющая широкие возможности для анализа данных. С ее помощью очень удобно загружать, обрабатывать и анализировать табличные данные с помощью SQL-подобных запросов. В связке с библиотеками Matplotlib и Seaborn появляется возможность удобного визуального анализа табличных данных (данные библиотеки включены в следующий уровень assessment'а).

#### 6. Чтение и первичная информация о файле
Выведите первые 15 значений (строк) датафрейма, полученного из файла 'adult.data' 

In [38]:
# читаем файл и загоняем в датафрейм
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None)
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 
'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']

In [13]:
df.head(15)

age          workclass  fnlwgt      education  education-num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   

            marital-status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   

                   race      sex  capital-gain  capital-loss  hours-per-week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0              50   
14   Asian-Pac-Islander     Male             0             0              40   

    native-country  salary  
0    United-States   <=50K  
1    United-States   <=50K  
2    United-States   <=50K  
3    United-States   <=50K  
4             Cuba   <=50K  
5    United-States   <=50K  
6          Jamaica   <=50K  
7    United-States    >50K  
8    United-States    >50K  
9    United-States    >50K  
10   United-States    >50K  
11           India    >50K  
12   United-States   <=50K  
13   United-States   <=50K  
14               ?    >50K

Каждая строка данного фрейма - это участник социологического опроса, проведённого в Америке 

#### 7. Индексация с условием
Вынесите в новый датафрейм с названием df_work мужчин (признак *sex*) старше 35 (признак *age*)  

In [14]:
# Т.к. в df.sex содержатся строки с лишними пробелами, при сравнении со строкой 'Male' будем удалять их из строки
df_work = df[(df.sex.apply(lambda x: x.replace(' ', '')) == 'Male') & (df.age > 35)]
df_work

#### 8. Группировка и меры центральной тенденции 
Сгруппируйте всех опрошенных по уровню образования (признак *education*) и найдите среднее значение по каждому из числовых (type = int) столбцов в каждой из получившихся групп

In [15]:
df.groupby('education').mean()

age         fnlwgt  education-num  capital-gain  \
education                                                              
 10th          37.429796  196832.465166            6.0    404.574491   
 11th          32.355745  194928.077447            7.0    215.097872   
 12th          32.000000  199097.508083            8.0    284.087760   
 1st-4th       46.142857  239303.000000            2.0    125.875000   
 5th-6th       42.885886  232448.333333            3.0    176.021021   
 7th-8th       48.445820  188079.171827            4.0    233.939628   
 9th           41.060311  202485.066148            5.0    342.089494   
 Assoc-acdm    37.381443  193424.093721           12.0    640.399250   
 Assoc-voc     38.553546  181936.016643           11.0    715.051375   
 Bachelors     38.904949  188055.914846           13.0   1756.299533   
 Doctorate     47.702179  186698.760291           16.0   4770.145278   
 HS-grad       38.974479  189538.739739            9.0    576.800114   
 Masters       44.049913  179852.362739           14.0   2562.563552   
 Preschool     42.764706  235889.372549            1.0    898.392157   
 Prof-school   44.746528  185663.706597           15.0  10414.416667   
 Some-college  35.756275  188742.922370           10.0    598.824167   

               capital-loss  hours-per-week  
education                                    
 10th             56.845659       37.052519  
 11th             50.079149       33.925957  
 12th             32.337182       35.780600  
 1st-4th          48.327381       38.255952  
 5th-6th          68.252252       38.897898  
 7th-8th          65.668731       39.366873  
 9th              28.998054       38.044747  
 Assoc-acdm       93.418932       40.504217  
 Assoc-voc        72.754703       41.610709  
 Bachelors       118.350327       42.614006  
 Doctorate       262.845036       46.973366  
 HS-grad          70.466622       40.575374  
 Masters         166.719675       43.836332  
 Preschool        66.490196       36.647059  
 Prof-school     231.203125       47.425347  
 Some-college     71.637087       38.852284

#### 9. Объединения и слияния
Объедините имеющийся датафрейм adult.data с прописанными ниже df_2 (новая колонка) и df_3 (новая строка), затем отсортируйте по признаку *age*

In [34]:
df_2 = pd.DataFrame({'random_column': np.random.rand(32561)})
df_3 = pd.DataFrame({'age': 40, 'workclass': 'Self-emp-not-inc', 'fnlwgt': 135415, 'education': 'Some-college', 'education-num': 10, 'marital-status': 'Married-civ-spouse', 'occupation': 'Other-service', 'relationship': 'Wife', 'race': 'White', 'sex': 'Female', 'capital-gain': 0, 'capital-loss': 0, 'hours-per-week': 5, 'native-country': 'United-States', 'salary': '<=50K'}, index=[32562])

df = df.merge(df_2, right_index = True, left_index = True)
df = df.merge(df_3, how = 'outer')
df = df.sort_values(by = 'age')
df

age          workclass  fnlwgt      education  education-num  \
6895    17            Private  100828   Some-college             10   
14907   17            Private  327127           11th              7   
7788    17            Private  287160           11th              7   
12919   17            Private   75333           10th              6   
7764    17            Private  154398           11th              7   
26800   17            Private  160758           10th              6   
26814   17            Private  101626            9th              5   
23178   17            Private  132636           11th              7   
21557   17                  ?  241021           12th              8   
7672    17                  ?  659273           11th              7   
7653    17            Private  221129            9th              5   
26874   17        Federal-gov   99893           11th              7   
22965   17            Private   54257           11th              7   
26905   17            Private  220562            9th              5   
31774   17                  ?  256173           10th              6   
19016   17            Private  198830           11th              7   
26969   17            Private  108273           10th              6   
26871   17            Private  238628           11th              7   
14862   17       Self-emp-inc  413557            9th              5   
7957    17            Private  186067           10th              6   
31866   17            Private  214787           12th              8   
8302    17            Private  342752           11th              7   
804     17            Private  193830           11th              7   
26423   17                  ?   67808           10th              6   
14699   17                  ?  303317           11th              7   
814     17            Private   32607           10th              6   
22936   17                  ?  332666           10th              6   
14731   17            Private   99462           11th              7   
840     17            Private  198124           11th              7   
8140    17            Private  111332           11th              7   
...    ...                ...     ...            ...            ...   
18845   90            Private  115306        Masters             14   
6631    90            Private  313986           11th              7   
6239    90   Self-emp-not-inc  155981      Bachelors             13   
32368   90          Local-gov  214594        7th-8th              4   
32278   90            Private  313749        HS-grad              9   
22231   90            Private   52386      Bachelors             13   
5373    90          Local-gov  227796        Masters             14   
28469   90        Federal-gov  195433        HS-grad              9   
15367   90            Private   90523        HS-grad              9   
11524   90            Private   87285        HS-grad              9   
12987   90            Private  250832           10th              6   
18292   90            Private  311184      Bachelors             13   
15903   90            Private   88991      Bachelors             13   
24246   90                  ?  166343        1st-4th              2   
12463   90                  ?  225063   Some-college             10   
31032   90            Private   47929        HS-grad              9   
20623   90            Private  206667        Masters             14   
5409    90            Private   51744        Masters             14   
1935    90            Private  221832      Bachelors             13   
10221   90   Self-emp-not-inc  282095   Some-college             10   
5275    90            Private  141758            9th              5   
25311   90                  ?  175444        7th-8th              4   
18738   90          Local-gov  153602        HS-grad              9   
4111    90                  ?  256514      Bachelors             13   
4072    90            Private  

#### 10. Применение функций 
Замените каждое значение в каждом из числовых (type == int) столбцов на среднеквадратичное отклонение по этому столбцу

In [36]:
# Используем несмещённую оценку (значение по-умолчанию в DataFrame.std(), параметр: ddof=1)
for i in df.select_dtypes('number').columns:
    df[i] = df[i].std()
df

age          workclass        fnlwgt      education  \
6895   1.776384e-15            Private  4.365642e-11   Some-college   
14907  1.776384e-15            Private  4.365642e-11           11th   
7788   1.776384e-15            Private  4.365642e-11           11th   
12919  1.776384e-15            Private  4.365642e-11           10th   
7764   1.776384e-15            Private  4.365642e-11           11th   
26800  1.776384e-15            Private  4.365642e-11           10th   
26814  1.776384e-15            Private  4.365642e-11            9th   
23178  1.776384e-15            Private  4.365642e-11           11th   
21557  1.776384e-15                  ?  4.365642e-11           12th   
7672   1.776384e-15                  ?  4.365642e-11           11th   
7653   1.776384e-15            Private  4.365642e-11            9th   
26874  1.776384e-15        Federal-gov  4.365642e-11           11th   
22965  1.776384e-15            Private  4.365642e-11           11th   
26905  1.776384e-15            Private  4.365642e-11            9th   
31774  1.776384e-15                  ?  4.365642e-11           10th   
19016  1.776384e-15            Private  4.365642e-11           11th   
26969  1.776384e-15            Private  4.365642e-11           10th   
26871  1.776384e-15            Private  4.365642e-11           11th   
14862  1.776384e-15       Self-emp-inc  4.365642e-11            9th   
7957   1.776384e-15            Private  4.365642e-11           10th   
31866  1.776384e-15            Private  4.365642e-11           12th   
8302   1.776384e-15            Private  4.365642e-11           11th   
804    1.776384e-15            Private  4.365642e-11           11th   
26423  1.776384e-15                  ?  4.365642e-11           10th   
14699  1.776384e-15                  ?  4.365642e-11           11th   
814    1.776384e-15            Private  4.365642e-11           10th   
22936  1.776384e-15                  ?  4.365642e-11           10th   
14731  1.776384e-15            Private  4.365642e-11           11th   
840    1.776384e-15            Private  4.365642e-11           11th   
8140   1.776384e-15            Private  4.365642e-11           11th   
...             ...                ...           ...            ...   
18845  1.776384e-15            Private  4.365642e-11        Masters   
6631   1.776384e-15            Private  4.365642e-11           11th   
6239   1.776384e-15   Self-emp-not-inc  4.365642e-11      Bachelors   
32368  1.776384e-15          Local-gov  4.365642e-11        7th-8th   
32278  1.776384e-15            Private  4.365642e-11        HS-grad   
22231  1.776384e-15            Private  4.365642e-11      Bachelors   
5373   1.776384e-15          Local-gov  4.365642e-11        Masters   
28469  1.776384e-15        Federal-gov  4.365642e-11        HS-grad   
15367  1.776384e-15            Private  4.365642e-11        HS-grad   
11524  1.776384e-15            Private  4.365642e-11        HS-grad   
12987  1.776384e-15            Private  4.365642e-11           10th   
18292  1.776384e-15            Private  4.365642e-11      Bachelors   
15903  1.776384e-15            Private  4.365642e-11      Bachelors   
24246  1.776384e-15                  ?  4.365642e-11        1st-4th   
12463  1.776384e-15                  ?  4.365642e-11   Some-college   
31032  1.776384e-15            Private  4.365642e-11        HS-grad   
20623  1.776384e-15            Private  4.365642e-11        Masters   
5409   1.776384e-15            Private  4.365642e-11        Masters   
1935   1.776384e-15            Private  4.365642e-11      Bachelors   
10221  1.776384e-15   Self-emp-not-inc  4.365642e-11   Some-college   
5275   1.776384e-15            Private  4.365642e-11            9th   
25311  1.776384e-15                  ?  4.365642e-11        7th-8th   
18738  1.776384e-15          Local-gov  4.365642e-11        HS-grad   
4111   1.776384e-15                  ?  4.365642e-11      Bachelors   
4072   1.776384e-15            Private  

<center style="background-color: #23B04A; color: white; font-size: 16px"><b>Анализ данных по доходу населения UCI Adult</b></center>

### Практические задания:

#### Обновляем файл adult.data и решаем задания ниже на нём

Уникальные значения признаков в датафрейме:
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

#### 11. Каков средний возраст (признак *age*) мужчин?

In [135]:
np.mean(df[df.sex.apply(lambda x: x.replace(' ', '')) == 'Male'].age)

39.43354749885268

**12. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год? **

In [140]:
print(df.groupby('salary').age.mean())

# Используем несмещённую оценку (значение по-умолчанию в DataFrame.std(), параметр: ddof=1)
print(df.groupby('salary').age.std())

salary
 <=50K    36.783738
 >50K     44.249841
Name: age, dtype: float64
salary
 <=50K    14.020088
 >50K     10.519028
Name: age, dtype: float64


**13. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [145]:
df[df.race.apply(lambda x: x.replace(' ', '')) == 'Amer-Indian-Eskimo'].age.max()

82

**14. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много (*salary* >50k)?**

In [41]:
max_hours = df['hours-per-week'].max() # Максимальное значение в столбце hours-per-week
print(max_hours)
max_hours_df = df[df['hours-per-week'] == max_hours]
print(len(max_hours_df.index)) # Количество записей в DataFrame со значением max_hours в столбце hours-per-week
# Делим количество записей в каждой группе на общее количество записей со значением max_hours в столбце hours-per-week
print(max_hours_df.groupby('salary').size() / len(max_hours_df) * 100) 

99
85
salary
 <=50K    70.588235
 >50K     29.411765
dtype: float64


**15. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [42]:
df.groupby(['native-country', 'salary'])['hours-per-week'].mean()

native-country               salary
 ?                            <=50K    40.164760
                              >50K     45.547945
 Cambodia                     <=50K    41.416667
                              >50K     40.000000
 Canada                       <=50K    37.914634
                              >50K     45.641026
 China                        <=50K    37.381818
                              >50K     38.900000
 Columbia                     <=50K    38.684211
                              >50K     50.000000
 Cuba                         <=50K    37.985714
                              >50K     42.440000
 Dominican-Republic           <=50K    42.338235
                              >50K     47.000000
 Ecuador                      <=50K    38.041667
                              >50K     48.750000
 El-Salvador                  <=50K    36.030928
                              >50K     45.000000
 England                      <=50K    40.483333
                              >50